title: "Privatpraxis Dr. med. Jütz"
description: "Hausbesuche & Telemedizin in Berlin · Arzt & Radioonkologie"
url: "https://martinjuetz.github.io/medicalJuetz"
baseurl: "/medicalJuetz"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

google_analytics: ""
markdown: kramdown
